[package]
name = "cloudflare-rust"
version = "0.1.0"
authors = ["Areg Harutyunyan <areg@cloudflare.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
slog = "2.4"
slog-term = "2.4"
sloggers = "0.3"
